#!/bin/sh

TEST_HTTPD_PORT=8081

perl -MTestHTTPD -e "TestHTTPD::httpd(port => ${TEST_HTTPD_PORT})" &
TEST_HTTPD_PID=$!

echo -n "Wait for TestHTTPD to start"
until netstat -ltn | grep -q :${TEST_HTTPD_PORT}; do
    echo -n .
done

echo ""

# Run apache bench
ab -n 65536 -c 256 http://127.0.0.1:${TEST_HTTPD_PORT}/
RESULT=$?

# Cleanup TestHTTPD
kill ${TEST_HTTPD_PID}
wait ${TEST_HTTPD_PID}

exit ${RESULT}
